### ISSUE TITLE
Cannot read properties of undefined (reading 'canonicalFeedOrder')

### ISSUE THREAD

**Issue by ftso-eu** [flare-foundation/FTSO-Scaling#1]
https://github.com/flare-foundation/FTSO-Scaling/blob/d59d500f8033252ee806a5d613e55c6cfebd881e/apps/ftso-data-provider/src/ftso-data-provider.service.ts#L67

 [Nest] 179726  - 03/13/2024, 6:26:45 PM   ERROR [ExceptionsHandler] Cannot read properties of undefined (reading 'canonicalFeedOrder')
 TypeError: Cannot read properties of undefined (reading 'canonicalFeedOrder')
 at FtsoDataProviderService.getCommitData (app/apps/ftso-data-provider/src/ftso-data-provider.service.ts:67:80)
at processTicksAndRejections (node:internal/process/task_queues:95:5)
  at FtsoDataProviderController.submit1 (app/apps/ftso-data-provider/src/ftso-data-provider.controller.ts:41:18)

**Comment by big14way** [comment]
i can fix this issue please assign me i am in the fellowship

**Comment by francojaf** [comment]
async getCommitData(
  votingRoundId: number,
  submissionAddress: string
): Promise<IPayloadMessage<ICommitData> | undefined> {
  const rewardEpoch = await this.rewardEpochManager.getRewardEpoch(votingRoundId);
  
  // ✅ Validar que exista
  if (!rewardEpoch) {
    this.logger.error(`No reward epoch found for voting round ${votingRoundId}`);
    return undefined;
  }

  const revealData = await this.getPricesForEpoch(votingRoundId, rewardEpoch.canonicalFeedOrder);
  // ... resto del código
}
